env:
  node: true
  es2020: true
  jest/globals: true
plugins:
  - promise
  - jest
extends:
  - airbnb-base
  - plugin:you-dont-need-lodash-underscore/compatible
  - plugin:jest/recommended
  - prettier
parserOptions:
  ecmaVersion: 11
  sourceType: module
